name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make file
        run: |
          expr 90 + 2 > docs/math.txt

      - name: listing
        run: ls docs

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: docs

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: downlad artifact for job 1
        uses: actions/download-artifact@v2
        with:
          name: homework
          path: docs

      - name: Listing
        run: ls docs

      - name: check zip version
        run: zip --version

      - name: zip release
        run: zip -r dist.zip docs

      - name: moving to dist
        run: |
          mkdir dist
          mv dist.zip dist

      - name: List after zipping
        run: ls dist

      - name: Upload dist
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/dist.zip
          tag: v1
          overwrite: true
          body: "lorem ipsum"

